import type { Metadata } from "next";
import Providers from "@/components/providers";
import "./globals.css";
import { Roboto } from "next/font/google";

import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
  title: "Relight fire",
  description: "Generated by create next app",
};
const font = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <TopNav></TopNav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
